typography_spectrum: 0.518092
color:
  brandColors:
    - '#000014'
    - '#FCFFFF'
    - '#614E54'
    - '#A5A27F'
    - '#78021C'
  brandStrength: 0.605263
  lightness: 0.10773
  rhythmicContrast: 0.207237
  saturation: 0.249178
opengraph: {}
layout_spectrum: 0.598509
analytics: {}
name: Millicent Brasserie
cta: {}
title: Oklahoma's first and only multi-sensory restaurant
purpose: {}
